abbreviations = {
	"IEEE": "Institute of Electrical and Electronics Engineers",
	"IT": "Information Technology",
	"UML": "Unified Modeling Language",
	"GUI": "Graphical User Interface",
	"SQA": "Software Quality Assurance",
	"CMMI": "Capability Maturity Model Integration",
	"SEI": "Software Engineering Institute",
	"WBS": "Work Breakdown Structure",
	"UP": "Unified Process",
	"XP": "Extreme Programming",
	"WIP": "Work in Progress",
	"CI": "Continuous Integration",
	"DevOps": "Development and Operations",
	"CRC": "Class-Responsibility-Collaboration",
	"QA": "Quality Assurance",
	"SWEBOK": "Software Engineering Body of Knowledge",
	"GSD": "Global Software Development",
	"LOC": "Lines of Code",
	"CHI": "Computer-Human Interaction",
	"SoC": "Separation of Concerns",
	"NFR": "Nonfunctional Requirements",
	"SCM": "Software Configuration Management",
	"PC": "Personal Computer",
	"PHTRS": "Public Works Department Repair System",
	"UI": "User Interface",
	"UX": "User Experience",
	"AD": "Architecture Description", 
	"ADL": "Architectural Description Language",
	"AI": "Artificial Intelligence",
	"ADR": "Architectural Decision Record",
	"ACD": "Architectural Context Diagram",
	"AOD": "Aspect-Oriented-Design",
	"SOAD": "Service-Oriented Architecture Decision",
	"PBAR": "Pattern-Based Architecture Review",
	"MVC": "Model-View-Controller",
	"OMG": "Object Management Group",
	"CBSE": "Component-Based Software Engineering",
	"OCP": "Open-Closed Principle",
	"DIP": "Dependency Inversion Principle",
	"LSP": "Liskov Substitution Principle",
	"UCD": "User-Centered Design",
	"WIMP": "Windows, Icons, Menus, Pointer",
	"HCI": "Human-Computer Interaction",
	"IA": "Information Architecture",
	"AR": "Augmented Reality",
	"VR": "Virtual Reality",
	"W3C": "World Wide Web Consortium",
	"UXD": "User Experience Design",
	"SaaS": "Software as a Service",
	"PaaS": "Platform as a Service",
	"IaaS": "Infrastructure as a Service",
	"HTML": "HyperText Markup Language",
	"CSS": "Cascading Style Sheets",
	"XML": "Extensible Markup Language",
	"SDK": "Software Development Kit",
	"GoF": "Gang of Four",
	"MSDN": "Microsoft Developer Network",
	"ISO": "International Organization for Standardization",
	"MTTF": "Mean Time to Failure",
	"MTTR": "Mean Time to Repair",
	"MTBF": "Mean Time Between Failures",
	"FTR": "Formal Technical Review",
	"PME": "Postmortem Evaluation",
	"SDL": "Security Development Lifecycle",
	"BSIMM": "Building Security In Maturity Model",
	"SAMM": "Software Assurance Maturity Model",
	"OWASP": "Open Web Application Security Project",
	"PII": "Personally Identifiable Information",
	"SQUARE": "Security Quality Requirements Engineering",
	"BVA": "Boundary Value Analysis",
	"V&V": "Verification and Validation",
	"BVT": "Boundary Value Testing",
	"CFT": "Component Functional Testing",
	"UT": "Unit Testing",
	"ITG": "Independent Test Group",
	"OO": "Object-Oriented",
	"I/O": "Input/Output",
	"WDPM": "Weighted Device Platform Matrix",
	"RDA": "Remote Data Access",
	"NPC": "Non-Playing Character",
	"HUD": "Heads-Up Display",
	"SCI": "Software Configuration Item",
	"CMS": "Content Management System",
	"ECO": "Engineering Change Order",
	"CCA": "Change Control Authority",
	"KLOC": "Thousand Lines of Code",
	"FP": "Function Points",
	"DRE": "Defect Removal Efficiency",
	"SMI": "Software Maturity Index",
	"KPIs": "Key Performance Indicators",
	"SSPI": "Statistical Software Process Improvement",
	"KPAs": "Key Practice Areas",
	"RMMM": "Risk Mitigation, Monitoring, and Management",
	"OCI": "Output/Control/Input",
	"TR": "Task Refinement",
	"SEE": "Software Engineering Environment",
	"PNR": "Putnam-Norden-Rayleigh curve",
	"RE": "Risk Exposure",
	"RIS": "Risk Information Sheet",
	"PS": "Project Size",
	"BU": "Business",
	"DE": "Development Environment",
	"ST": "Staffing",
	"SACA": "Static Architecture-Conformance Analysis",
	"SPI": "Software Process Improvement",
	"SPICE": "Software Process Improvement and Capability Determination",
	"ROI": "Return on Investment",
	"IDE": "Integrated Development Environment",
	"TDD": "Test-Driven Development"
}