name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main  # Triggers the workflow on pushes to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code from the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up Docker Buildx (for multi-platform builds)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Step 3: Log in to Docker Hub using secrets
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Step 4: Build and push the Docker image to Docker Hub
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .  # This is where the Dockerfile is located (root directory of your repository)
        platforms: linux/amd64,linux/arm64  # Ensures compatibility for both x86 and ARM architectures
        push: true  # This pushes the image to Docker Hub
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/team3-app:latest  # Tag the image as latest
          ${{ secrets.DOCKERHUB_USERNAME }}/team3-app:${{ github.sha }}  # Tag the image with the commit SHA

    # Step 5: Output the Docker image digest (optional but useful)
    - name: Output image digest
      run: echo "Docker image digest: ${{ steps.build-and-push.outputs.digest }}"
