name: Docker Image CI

on:
  push:
    branches: 
      - "main"

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}  # Ensure you set these secrets in your repo settings
    
    - name: Lowercase the repo name
      run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

    - name: Create .env file
      run: echo "MISTRAL_API_KEY=${{ secrets.MISTRAL_API_KEY }}" > .env

    - name: Install Mambaforge
      run: |
        wget -q "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Linux-x86_64.sh" -O mambaforge.sh
        bash mambaforge.sh -b -p $HOME/mambaforge
        echo "$HOME/mambaforge/bin" >> $GITHUB_PATH

    - name: Create Mamba environment
      run: |
        source $HOME/mambaforge/bin/activate
        mamba init bash
        mamba create -n team3_env python=3.11 -y
        mamba install --yes --file requirements.txt
      shell: bash

    - name: Build and push Docker image
      id: docker_build  # Assigning an ID for this step to reference its outputs
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          docker.io/${{ secrets.DOCKERHUB_USERNAME }}/team3-app:latest
      env:
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Image digest
      run: echo "Image Digest: ${{ steps.docker_build.outputs.digest }}"
